$(document).ready(function(){
	$('#disinfectorModel').textbox({
		prompt:'请输入型号'
	});
	$('#shelflife').textbox({
		prompt:'请输入保质期'
	});
	$('#pack').textbox({
		prompt:'请输入包装'
	});
	$('#disinfectorType').textbox({
		prompt:'请输入类别'
	});
	$('#xjfzt').textbox({
		prompt:'请输入细菌繁殖体'
	});
	$('#fzgj').textbox({
		prompt:'请输入分支杆菌'
	});
	$('#zj').textbox({
		prompt:'请输入真菌'
	});
	$('#bmbd').textbox({
		prompt:'请输入包膜病毒'
	});
	$('#fbmbd').textbox({
		prompt:'请输入非包膜病毒'
	});
	$('#bz').textbox({
		prompt:'请输入孢子'
	});
	$('#yjw').textbox({
		prompt:'请输入有机物存在时的效果'
	});
	$('#ys').textbox({
		prompt:'请输入硬水存在时的效果'
	});
	$('#xdj').textbox({
		prompt:'请输入有肥皂或洗涤剂存在时的效果'
	});
	$('#apperance').textbox({
		prompt:'请输入性状',
		multiline:true
	});
	$('#effect').textbox({
		prompt:'请输入作用机理',
		multiline:true
	});
	$('#advantage').textbox({
		prompt:'请输入优点',
		multiline:true
	});
	$('#disadvantage').textbox({
		prompt:'请输入缺点',
		multiline:true
	});
	$('#usageDosage').textbox({
		prompt:'请输入使用方法',
		multiline:true
	});
	$('#notice').textbox({
		prompt:'请输入注意事项',
		multiline:true
	});
	/*$('#notes').textbox({
		prompt:'请输入备注',
		multiline:true
	});*/
});